# -*- coding: utf-8 -*-
"""geo_data.py - Built-in coarse-grained geographic data for geo-evidence-audit.

PURE DATA MODULE - no logic, no I/O, no network access.

Data content:
  - 60 countries: ISO 3166 alpha-2, calling codes, currencies, UTC offsets,
    approximate bounding boxes, bilingual (en/zh) city name lists.
  - Currency symbols, country name aliases, IANA time zone -> UTC offset map.
  - Counter-example protection data: eurozone members, multi-timezone countries.

Provenance, fetch dates (2026-08-30) and evidence-strength labels for every
data class live in references/data-provenance.md. Bounding boxes and city
lists are APPROXIMATE and marked "unverified/approximate" there; bbox checks
are country-level coarse bounding boxes, NOT precise reverse geocoding.
"""

from dataclasses import dataclass, field


@dataclass
class CountryInfo:
    iso2: str
    name_en: str
    name_zh: str
    calling_codes: list = field(default_factory=list)
    currencies: list = field(default_factory=list)
    # UTC offset in hours (float, negative west of Greenwich).
    tz_offsets: list = field(default_factory=list)
    # (min_lon, min_lat, max_lon, maxlat) approximate bounding box.
    bbox: tuple = ()
    cities_en: list = field(default_factory=list)
    cities_zh: list = field(default_factory=list)


# Currency symbol -> ISO 4217 codes that may use it (ambiguous symbols map
# to several codes; rules treat any match as consistent).
CURRENCY_SYMBOLS = {
    "$": ["USD", "AUD", "CAD", "NZD", "SGD", "HKD", "MXN", "ARS", "CLP", "COP", "PHP"],
    "€": ["EUR"],
    "£": ["GBP"],
    "¥": ["CNY", "JPY"],
    "₩": ["KRW"],
    "₹": ["INR"],
    "₽": ["RUB"],
    "₺": ["TRY"],
    "₫": ["VND"],
    "฿": ["THB"],
    "₴": ["UAH"],
    "₱": ["PHP"],
}

# Common country name aliases (lowercase) -> ISO 3166 alpha-2.
COUNTRY_ALIASES = {
    "usa": "US",
    "u.s.a.": "US",
    "united states": "US",
    "united states of america": "US",
    "uk": "GB",
    "u.k.": "GB",
    "united kingdom": "GB",
    "great britain": "GB",
    "britain": "GB",
    "uae": "AE",
    "south korea": "KR",
    "korea": "KR",
    "republic of korea": "KR",
    "russia": "RU",
    "russian federation": "RU",
    "holland": "NL",
    "the netherlands": "NL",
    "czech republic": "CZ",
    "vietnam": "VN",
    "switzerland": "CH",
    "new york city": "US",
}

# Eurozone members (ISO 4217 "EUR" legal tender). Counter-example protection
# for rule R3: eurozone members paying in EUR must NOT trigger a finding.
# Source: European Central Bank, fetched 2026-08-30 (see data-provenance.md).
EUROZONE_MEMBERS = {
    "AT", "BE", "HR", "CY", "EE", "FI", "FR", "DE", "GR", "IE", "IT",
    "LV", "LT", "LU", "MT", "NL", "PT", "SK", "SI", "ES",
}

# Countries spanning multiple UTC offsets. Counter-example protection for
# rule R2: any one of the country's listed offsets matching is consistent
# (e.g. US offices on UTC-7 must not trigger against UTC-5).
MULTI_TZ_COUNTRIES = {"US", "CA", "RU", "ID", "AU", "MX", "BR", "KZ", "CL"}

# IANA time zone name -> UTC offset in hours (standard time, no DST).
# Subset covering the zones referenced by the built-in country data.
IANA_TZ_OFFSETS = {
    "Asia/Shanghai": 8.0,
    "Asia/Hong_Kong": 8.0,
    "Asia/Tokyo": 9.0,
    "Asia/Seoul": 9.0,
    "Asia/Singapore": 8.0,
    "Asia/Kuala_Lumpur": 8.0,
    "Asia/Bangkok": 7.0,
    "Asia/Ho_Chi_Minh": 7.0,
    "Asia/Jakarta": 7.0,
    "Asia/Makassar": 8.0,
    "Asia/Jayapura": 9.0,
    "Asia/Manila": 8.0,
    "Asia/Kolkata": 5.5,
    "Asia/Calcutta": 5.5,
    "Asia/Karachi": 5.0,
    "Asia/Dhaka": 6.0,
    "Asia/Colombo": 5.5,
    "Asia/Kathmandu": 5.75,
    "Asia/Dubai": 4.0,
    "Asia/Riyadh": 3.0,
    "Asia/Qatar": 3.0,
    "Asia/Jerusalem": 2.0,
    "Asia/Almaty": 5.0,
    "Asia/Tashkent": 5.0,
    "Asia/Yangon": 6.5,
    "Europe/London": 0.0,
    "Europe/Dublin": 0.0,
    "Europe/Lisbon": 0.0,
    "Europe/Paris": 1.0,
    "Europe/Berlin": 1.0,
    "Europe/Madrid": 1.0,
    "Europe/Rome": 1.0,
    "Europe/Amsterdam": 1.0,
    "Europe/Brussels": 1.0,
    "Europe/Zurich": 1.0,
    "Europe/Vienna": 1.0,
    "Europe/Warsaw": 1.0,
    "Europe/Stockholm": 1.0,
    "Europe/Oslo": 1.0,
    "Europe/Copenhagen": 1.0,
    "Europe/Prague": 1.0,
    "Europe/Budapest": 1.0,
    "Europe/Luxembourg": 1.0,
    "Europe/Helsinki": 2.0,
    "Europe/Athens": 2.0,
    "Europe/Bucharest": 2.0,
    "Europe/Kyiv": 2.0,
    "Europe/Kiev": 2.0,
    "Europe/Moscow": 3.0,
    "Europe/Istanbul": 3.0,
    "Africa/Cairo": 2.0,
    "Africa/Lagos": 1.0,
    "Africa/Casablanca": 1.0,
    "Africa/Nairobi": 3.0,
    "Africa/Johannesburg": 2.0,
    "America/New_York": -5.0,
    "America/Toronto": -5.0,
    "America/Chicago": -6.0,
    "America/Winnipeg": -6.0,
    "America/Mexico_City": -6.0,
    "America/Denver": -7.0,
    "America/Phoenix": -7.0,
    "America/Edmonton": -7.0,
    "America/Los_Angeles": -8.0,
    "America/Vancouver": -8.0,
    "America/Anchorage": -9.0,
    "America/Halifax": -4.0,
    "America/St_Johns": -3.5,
    "America/Sao_Paulo": -3.0,
    "America/Buenos_Aires": -3.0,
    "America/Santiago": -4.0,
    "America/Bogota": -5.0,
    "America/Lima": -5.0,
    "UTC": 0.0,
    "GMT": 0.0,
    "Australia/Sydney": 10.0,
    "Australia/Melbourne": 10.0,
    "Australia/Brisbane": 10.0,
    "Australia/Hobart": 10.0,
    "Australia/Adelaide": 9.5,
    "Australia/Darwin": 9.5,
    "Australia/Perth": 8.0,
    "Pacific/Auckland": 12.0,
}

# IANA time zone name -> primary ISO 3166 alpha-2 country (well-known
# home country of the zone). Used only for corroboration (R7), not for
# contradiction checks.
IANA_TZ_COUNTRY = {
    "Asia/Shanghai": "CN",
    "Asia/Hong_Kong": "HK",
    "Asia/Tokyo": "JP",
    "Asia/Seoul": "KR",
    "Asia/Singapore": "SG",
    "Asia/Kuala_Lumpur": "MY",
    "Asia/Bangkok": "TH",
    "Asia/Ho_Chi_Minh": "VN",
    "Asia/Jakarta": "ID",
    "Asia/Makassar": "ID",
    "Asia/Jayapura": "ID",
    "Asia/Manila": "PH",
    "Asia/Kolkata": "IN",
    "Asia/Calcutta": "IN",
    "Asia/Karachi": "PK",
    "Asia/Dhaka": "BD",
    "Asia/Colombo": "LK",
    "Asia/Kathmandu": "NP",
    "Asia/Dubai": "AE",
    "Asia/Riyadh": "SA",
    "Asia/Qatar": "QA",
    "Asia/Jerusalem": "IL",
    "Asia/Almaty": "KZ",
    "Asia/Tashkent": "UZ",
    "Asia/Yangon": "MM",
    "Europe/London": "GB",
    "Europe/Dublin": "IE",
    "Europe/Lisbon": "PT",
    "Europe/Paris": "FR",
    "Europe/Berlin": "DE",
    "Europe/Madrid": "ES",
    "Europe/Rome": "IT",
    "Europe/Amsterdam": "NL",
    "Europe/Brussels": "BE",
    "Europe/Zurich": "CH",
    "Europe/Vienna": "AT",
    "Europe/Warsaw": "PL",
    "Europe/Stockholm": "SE",
    "Europe/Oslo": "NO",
    "Europe/Copenhagen": "DK",
    "Europe/Prague": "CZ",
    "Europe/Budapest": "HU",
    "Europe/Luxembourg": "LU",
    "Europe/Helsinki": "FI",
    "Europe/Athens": "GR",
    "Europe/Bucharest": "RO",
    "Europe/Kyiv": "UA",
    "Europe/Kiev": "UA",
    "Europe/Moscow": "RU",
    "Europe/Istanbul": "TR",
    "Africa/Cairo": "EG",
    "Africa/Lagos": "NG",
    "Africa/Casablanca": "MA",
    "Africa/Nairobi": "KE",
    "Africa/Johannesburg": "ZA",
    "America/New_York": "US",
    "America/Toronto": "CA",
    "America/Chicago": "US",
    "America/Winnipeg": "CA",
    "America/Mexico_City": "MX",
    "America/Denver": "US",
    "America/Phoenix": "US",
    "America/Edmonton": "CA",
    "America/Los_Angeles": "US",
    "America/Vancouver": "CA",
    "America/Anchorage": "US",
    "America/Halifax": "CA",
    "America/St_Johns": "CA",
    "America/Sao_Paulo": "BR",
    "America/Buenos_Aires": "AR",
    "America/Santiago": "CL",
    "America/Bogota": "CO",
    "America/Lima": "PE",
    "Australia/Sydney": "AU",
    "Australia/Melbourne": "AU",
    "Australia/Brisbane": "AU",
    "Australia/Hobart": "AU",
    "Australia/Adelaide": "AU",
    "Australia/Darwin": "AU",
    "Australia/Perth": "AU",
    "Pacific/Auckland": "NZ",
}


def _c(iso2, name_en, name_zh, calling_codes, currencies, tz_offsets,
       bbox, cities_en, cities_zh):
    return CountryInfo(
        iso2=iso2, name_en=name_en, name_zh=name_zh,
        calling_codes=calling_codes, currencies=currencies,
        tz_offsets=tz_offsets, bbox=bbox,
        cities_en=cities_en, cities_zh=cities_zh,
    )


# 60 countries. tz_offsets = hours (float). bbox = (min_lon, min_lat,
# max_lon, max_lat), approximate coarse bounding box. City lists are
# representative major cities (en + zh), not exhaustive gazetteers.
COUNTRIES = {
    "US": _c("US", "United States", "美国", ["1"], ["USD"],
             [-5.0, -6.0, -7.0, -8.0, -9.0, -10.0], (-125.0, 24.0, -66.0, 50.0),
             ["New York", "Los Angeles", "Chicago", "Houston", "Phoenix",
              "Philadelphia", "San Francisco", "Seattle", "Boston", "Miami",
              "Denver", "Austin", "Dallas", "Atlanta", "Washington"],
             ["纽约", "洛杉矶", "芝加哥", "休斯顿", "凤凰城", "费城", "旧金山",
              "西雅图", "波士顿", "迈阿密", "丹佛", "奥斯汀", "达拉斯",
              "亚特兰大", "华盛顿"]),
    "CA": _c("CA", "Canada", "加拿大", ["1"], ["CAD"],
             [-8.0, -7.0, -6.0, -5.0, -4.0, -3.5], (-141.0, 42.0, -52.0, 84.0),
             ["Toronto", "Vancouver", "Montreal", "Calgary", "Ottawa",
              "Quebec", "Winnipeg", "Halifax"],
             ["多伦多", "温哥华", "蒙特利尔", "卡尔加里", "渥太华", "魁北克",
              "温尼伯", "哈利法克斯"]),
    "MX": _c("MX", "Mexico", "墨西哥", ["52"], ["MXN"],
             [-8.0, -7.0, -6.0, -5.0], (-118.0, 14.0, -86.0, 33.0),
             ["Mexico City", "Guadalajara", "Monterrey", "Cancun", "Tijuana"],
             ["墨西哥城", "瓜达拉哈拉", "蒙特雷", "坎昆", "蒂华纳"]),
    "BR": _c("BR", "Brazil", "巴西", ["55"], ["BRL"],
             [-5.0, -4.0, -3.0, -2.0], (-74.0, -34.0, -32.0, 6.0),
             ["Sao Paulo", "Rio de Janeiro", "Brasilia", "Salvador",
              "Fortaleza", "Recife"],
             ["圣保罗", "里约热内卢", "巴西利亚", "萨尔瓦多", "福塔莱萨",
              "累西腓"]),
    "AR": _c("AR", "Argentina", "阿根廷", ["54"], ["ARS"], [-3.0],
             (-74.0, -55.0, -53.0, -21.0),
             ["Buenos Aires", "Cordoba", "Rosario", "Mendoza"],
             ["布宜诺斯艾利斯", "科尔多瓦", "罗萨里奥", "门多萨"]),
    "GB": _c("GB", "United Kingdom", "英国", ["44"], ["GBP"], [0.0],
             (-8.0, 49.0, 2.0, 61.0),
             ["London", "Manchester", "Birmingham", "Edinburgh", "Glasgow",
              "Liverpool", "Leeds", "Bristol", "Cambridge", "Oxford"],
             ["伦敦", "曼彻斯特", "伯明翰", "爱丁堡", "格拉斯哥", "利物浦",
              "利兹", "布里斯托", "剑桥", "牛津"]),
    "IE": _c("IE", "Ireland", "爱尔兰", ["353"], ["EUR"], [0.0],
             (-11.0, 51.0, -6.0, 56.0),
             ["Dublin", "Cork", "Galway", "Limerick"],
             ["都柏林", "科克", "戈尔韦", "利默里克"]),
    "FR": _c("FR", "France", "法国", ["33"], ["EUR"], [1.0],
             (-5.0, 41.0, 10.0, 52.0),
             ["Paris", "Lyon", "Marseille", "Toulouse", "Nice", "Bordeaux",
              "Lille", "Strasbourg"],
             ["巴黎", "里昂", "马赛", "图卢兹", "尼斯", "波尔多", "里尔",
              "斯特拉斯堡"]),
    "DE": _c("DE", "Germany", "德国", ["49"], ["EUR"], [1.0],
             (5.0, 47.0, 16.0, 55.0),
             ["Berlin", "Munich", "Hamburg", "Frankfurt", "Cologne",
              "Stuttgart", "Duesseldorf", "Dresden", "Leipzig", "Nuremberg"],
             ["柏林", "慕尼黑", "汉堡", "法兰克福", "科隆", "斯图加特",
              "杜塞尔多夫", "德累斯顿", "莱比锡", "纽伦堡"]),
    "ES": _c("ES", "Spain", "西班牙", ["34"], ["EUR"], [1.0],
             (-19.0, 27.0, 5.0, 44.0),
             ["Madrid", "Barcelona", "Valencia", "Seville", "Bilbao",
              "Malaga", "Zaragoza"],
             ["马德里", "巴塞罗那", "瓦伦西亚", "塞维利亚", "毕尔巴鄂",
              "马拉加", "萨拉戈萨"]),
    "IT": _c("IT", "Italy", "意大利", ["39"], ["EUR"], [1.0],
             (6.0, 36.0, 19.0, 47.0),
             ["Rome", "Milan", "Naples", "Turin", "Florence", "Venice",
              "Bologna", "Genoa"],
             ["罗马", "米兰", "那不勒斯", "都灵", "佛罗伦萨", "威尼斯",
              "博洛尼亚", "热那亚"]),
    "NL": _c("NL", "Netherlands", "荷兰", ["31"], ["EUR"], [1.0],
             (3.0, 50.0, 8.0, 54.0),
             ["Amsterdam", "Rotterdam", "The Hague", "Utrecht", "Eindhoven"],
             ["阿姆斯特丹", "鹿特丹", "海牙", "乌得勒支", "埃因霍温"]),
    "BE": _c("BE", "Belgium", "比利时", ["32"], ["EUR"], [1.0],
             (2.0, 49.0, 7.0, 52.0),
             ["Brussels", "Antwerp", "Ghent", "Bruges", "Liege"],
             ["布鲁塞尔", "安特卫普", "根特", "布鲁日", "列日"]),
    "CH": _c("CH", "Switzerland", "瑞士", ["41"], ["CHF"], [1.0],
             (5.0, 45.0, 11.0, 48.0),
             ["Zurich", "Geneva", "Basel", "Bern", "Lausanne", "Lugano"],
             ["苏黎世", "日内瓦", "巴塞尔", "伯尔尼", "洛桑", "卢加诺"]),
    "AT": _c("AT", "Austria", "奥地利", ["43"], ["EUR"], [1.0],
             (9.0, 46.0, 17.0, 49.0),
             ["Vienna", "Salzburg", "Innsbruck", "Graz", "Linz"],
             ["维也纳", "萨尔茨堡", "因斯布鲁克", "格拉茨", "林茨"]),
    "PT": _c("PT", "Portugal", "葡萄牙", ["351"], ["EUR"], [0.0],
             (-10.0, 36.0, -6.0, 43.0),
             ["Lisbon", "Porto", "Braga", "Coimbra"],
             ["里斯本", "波尔图", "布拉加", "科英布拉"]),
    "PL": _c("PL", "Poland", "波兰", ["48"], ["PLN"], [1.0],
             (14.0, 49.0, 24.0, 55.0),
             ["Warsaw", "Krakow", "Gdansk", "Poznan", "Wroclaw", "Lodz"],
             ["华沙", "克拉科夫", "格但斯克", "波兹南", "弗罗茨瓦夫", "罗兹"]),
    "SE": _c("SE", "Sweden", "瑞典", ["46"], ["SEK"], [1.0],
             (11.0, 55.0, 24.0, 69.0),
             ["Stockholm", "Gothenburg", "Malmo", "Uppsala"],
             ["斯德哥尔摩", "哥德堡", "马尔默", "乌普萨拉"]),
    "NO": _c("NO", "Norway", "挪威", ["47"], ["NOK"], [1.0],
             (4.0, 57.0, 32.0, 71.0),
             ["Oslo", "Bergen", "Trondheim", "Stavanger"],
             ["奥斯陆", "卑尔根", "特隆赫姆", "斯塔万格"]),
    "DK": _c("DK", "Denmark", "丹麦", ["45"], ["DKK"], [1.0],
             (8.0, 54.0, 13.0, 58.0),
             ["Copenhagen", "Aarhus", "Odense", "Aalborg"],
             ["哥本哈根", "奥胡斯", "欧登塞", "奥尔堡"]),
    "FI": _c("FI", "Finland", "芬兰", ["358"], ["EUR"], [2.0],
             (20.0, 59.0, 32.0, 71.0),
             ["Helsinki", "Espoo", "Tampere", "Turku", "Oulu"],
             ["赫尔辛基", "埃斯波", "坦佩雷", "图尔库", "奥卢"]),
    "RU": _c("RU", "Russia", "俄罗斯", ["7"], ["RUB"],
             [2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0],
             (19.0, 41.0, 180.0, 82.0),
             ["Moscow", "Saint Petersburg", "Novosibirsk", "Yekaterinburg",
              "Kazan", "Vladivostok", "Sochi"],
             ["莫斯科", "圣彼得堡", "新西伯利亚", "叶卡捷琳堡", "喀山",
              "符拉迪沃斯托克", "索契"]),
    "UA": _c("UA", "Ukraine", "乌克兰", ["380"], ["UAH"], [2.0, 3.0],
             (22.0, 44.0, 40.0, 53.0),
             ["Kyiv", "Kharkiv", "Odesa", "Lviv"],
             ["基辅", "哈尔科夫", "敖德萨", "利沃夫"]),
    "TR": _c("TR", "Turkey", "土耳其", ["90"], ["TRY"], [3.0],
             (26.0, 36.0, 45.0, 43.0),
             ["Istanbul", "Ankara", "Izmir", "Antalya", "Bursa"],
             ["伊斯坦布尔", "安卡拉", "伊兹密尔", "安塔利亚", "布尔萨"]),
    "CN": _c("CN", "China", "中国", ["86"], ["CNY"], [8.0],
             (73.0, 18.0, 135.0, 54.0),
             ["Beijing", "Shanghai", "Guangzhou", "Shenzhen", "Hangzhou",
              "Chengdu", "Wuhan", "Xi'an", "Nanjing", "Chongqing", "Tianjin",
              "Suzhou", "Qingdao", "Dalian", "Xiamen"],
             ["北京", "上海", "广州", "深圳", "杭州", "成都", "武汉", "西安",
              "南京", "重庆", "天津", "苏州", "青岛", "大连", "厦门"]),
    "HK": _c("HK", "Hong Kong", "中国香港", ["852"], ["HKD"], [8.0],
             (113.0, 22.0, 115.0, 23.0),
             ["Hong Kong", "Kowloon", "Tsuen Wan", "Sha Tin"],
             ["香港", "九龙", "荃湾", "沙田"]),
    "JP": _c("JP", "Japan", "日本", ["81"], ["JPY"], [9.0],
             (122.0, 24.0, 146.0, 46.0),
             ["Tokyo", "Osaka", "Kyoto", "Yokohama", "Nagoya", "Sapporo",
              "Fukuoka", "Kobe", "Hiroshima", "Sendai"],
             ["东京", "大阪", "京都", "横滨", "名古屋", "札幌", "福冈",
              "神户", "广岛", "仙台"]),
    "KR": _c("KR", "South Korea", "韩国", ["82"], ["KRW"], [9.0],
             (124.0, 33.0, 132.0, 39.0),
             ["Seoul", "Busan", "Incheon", "Daegu", "Daejeon", "Gwangju"],
             ["首尔", "釜山", "仁川", "大邱", "大田", "光州"]),
    "SG": _c("SG", "Singapore", "新加坡", ["65"], ["SGD"], [8.0],
             (103.0, 1.0, 105.0, 2.0),
             ["Singapore"], ["新加坡"]),
    "MY": _c("MY", "Malaysia", "马来西亚", ["60"], ["MYR"], [8.0],
             (99.0, 1.0, 120.0, 8.0),
             ["Kuala Lumpur", "Penang", "Johor Bahru", "Malacca", "Ipoh"],
             ["吉隆坡", "槟城", "新山", "马六甲", "怡保"]),
    "TH": _c("TH", "Thailand", "泰国", ["66"], ["THB"], [7.0],
             (97.0, 5.0, 106.0, 21.0),
             ["Bangkok", "Chiang Mai", "Phuket", "Pattaya", "Krabi"],
             ["曼谷", "清迈", "普吉", "芭提雅", "甲米"]),
    "VN": _c("VN", "Vietnam", "越南", ["84"], ["VND"], [7.0],
             (102.0, 8.0, 110.0, 24.0),
             ["Hanoi", "Ho Chi Minh City", "Da Nang", "Hue", "Haiphong"],
             ["河内", "胡志明市", "岘港", "顺化", "海防"]),
    "PH": _c("PH", "Philippines", "菲律宾", ["63"], ["PHP"], [8.0],
             (116.0, 4.0, 127.0, 20.0),
             ["Manila", "Cebu", "Davao", "Quezon City"],
             ["马尼拉", "宿务", "达沃", "奎松城"]),
    "ID": _c("ID", "Indonesia", "印度尼西亚", ["62"], ["IDR"],
             [7.0, 8.0, 9.0], (94.0, -11.0, 142.0, 7.0),
             ["Jakarta", "Surabaya", "Bandung", "Medan", "Bali", "Denpasar"],
             ["雅加达", "泗水", "万隆", "棉兰", "巴厘岛", "登巴萨"]),
    "IN": _c("IN", "India", "印度", ["91"], ["INR"], [5.5],
             (68.0, 6.0, 98.0, 36.0),
             ["Mumbai", "Delhi", "New Delhi", "Bangalore", "Chennai",
              "Hyderabad", "Kolkata", "Pune", "Ahmedabad", "Jaipur"],
             ["孟买", "德里", "新德里", "班加罗尔", "金奈", "海得拉巴",
              "加尔各答", "浦那", "艾哈迈达巴德", "斋浦尔"]),
    "PK": _c("PK", "Pakistan", "巴基斯坦", ["92"], ["PKR"], [5.0],
             (60.0, 23.0, 78.0, 38.0),
             ["Karachi", "Lahore", "Islamabad", "Faisalabad"],
             ["卡拉奇", "拉合尔", "伊斯兰堡", "费萨拉巴德"]),
    "BD": _c("BD", "Bangladesh", "孟加拉国", ["880"], ["BDT"], [6.0],
             (88.0, 20.0, 93.0, 27.0),
             ["Dhaka", "Chittagong"], ["达卡", "吉大港"]),
    "LK": _c("LK", "Sri Lanka", "斯里兰卡", ["94"], ["LKR"], [5.5],
             (79.0, 5.0, 82.0, 10.0),
             ["Colombo", "Kandy"], ["科伦坡", "康提"]),
    "NP": _c("NP", "Nepal", "尼泊尔", ["977"], ["NPR"], [5.75],
             (80.0, 26.0, 89.0, 31.0),
             ["Kathmandu", "Pokhara"], ["加德满都", "博卡拉"]),
    "AU": _c("AU", "Australia", "澳大利亚", ["61"], ["AUD"],
             [8.0, 9.5, 10.0], (112.0, -44.0, 154.0, -10.0),
             ["Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide",
              "Canberra", "Gold Coast", "Darwin", "Hobart"],
             ["悉尼", "墨尔本", "布里斯班", "珀斯", "阿德莱德", "堪培拉",
              "黄金海岸", "达尔文", "霍巴特"]),
    "NZ": _c("NZ", "New Zealand", "新西兰", ["64"], ["NZD"],
             [12.0, 12.75, 13.0], (166.0, -48.0, 179.0, -34.0),
             ["Auckland", "Wellington", "Christchurch", "Hamilton",
              "Dunedin"],
             ["奥克兰", "惠灵顿", "基督城", "哈密尔顿", "但尼丁"]),
    "AE": _c("AE", "United Arab Emirates", "阿联酋", ["971"], ["AED"], [4.0],
             (51.0, 22.0, 57.0, 26.0),
             ["Dubai", "Abu Dhabi", "Sharjah", "Ajman"],
             ["迪拜", "阿布扎比", "沙迦", "阿治曼"]),
    "SA": _c("SA", "Saudi Arabia", "沙特阿拉伯", ["966"], ["SAR"], [3.0],
             (34.0, 16.0, 56.0, 32.0),
             ["Riyadh", "Jeddah", "Mecca", "Medina", "Dammam"],
             ["利雅得", "吉达", "麦加", "麦地那", "达曼"]),
    "QA": _c("QA", "Qatar", "卡塔尔", ["974"], ["QAR"], [3.0],
             (50.0, 24.0, 52.0, 27.0),
             ["Doha"], ["多哈"]),
    "IL": _c("IL", "Israel", "以色列", ["972"], ["ILS"], [2.0, 3.0],
             (34.0, 29.0, 36.0, 34.0),
             ["Jerusalem", "Tel Aviv", "Haifa"],
             ["耶路撒冷", "特拉维夫", "海法"]),
    "EG": _c("EG", "Egypt", "埃及", ["20"], ["EGP"], [2.0],
             (24.0, 22.0, 37.0, 32.0),
             ["Cairo", "Alexandria", "Giza", "Luxor"],
             ["开罗", "亚历山大", "吉萨", "卢克索"]),
    "ZA": _c("ZA", "South Africa", "南非", ["27"], ["ZAR"], [2.0],
             (16.0, -35.0, 33.0, -22.0),
             ["Johannesburg", "Cape Town", "Durban", "Pretoria"],
             ["约翰内斯堡", "开普敦", "德班", "比勒陀利亚"]),
    "NG": _c("NG", "Nigeria", "尼日利亚", ["234"], ["NGN"], [1.0],
             (2.0, 4.0, 15.0, 14.0),
             ["Lagos", "Abuja", "Kano"], ["拉各斯", "阿布贾", "卡诺"]),
    "KE": _c("KE", "Kenya", "肯尼亚", ["254"], ["KES"], [3.0],
             (33.0, -5.0, 43.0, 6.0),
             ["Nairobi", "Mombasa"], ["内罗毕", "蒙巴萨"]),
    "MA": _c("MA", "Morocco", "摩洛哥", ["212"], ["MAD"], [1.0],
             (-14.0, 27.0, -1.0, 36.0),
             ["Casablanca", "Rabat", "Marrakesh", "Fez"],
             ["卡萨布兰卡", "拉巴特", "马拉喀什", "非斯"]),
    "GR": _c("GR", "Greece", "希腊", ["30"], ["EUR"], [2.0],
             (19.0, 34.0, 28.0, 42.0),
             ["Athens", "Thessaloniki", "Piraeus"],
             ["雅典", "塞萨洛尼基", "比雷埃夫斯"]),
    "CZ": _c("CZ", "Czechia", "捷克", ["420"], ["CZK"], [1.0],
             (12.0, 48.0, 23.0, 52.0),
             ["Prague", "Brno", "Ostrava"],
             ["布拉格", "布尔诺", "俄斯特拉发"]),
    "HU": _c("HU", "Hungary", "匈牙利", ["36"], ["HUF"], [1.0],
             (16.0, 45.0, 23.0, 49.0),
             ["Budapest", "Debrecen", "Szeged"],
             ["布达佩斯", "德布勒森", "塞格德"]),
    "RO": _c("RO", "Romania", "罗马尼亚", ["40"], ["RON"], [2.0],
             (20.0, 43.0, 30.0, 49.0),
             ["Bucharest", "Cluj-Napoca", "Timisoara"],
             ["布加勒斯特", "克卢日", "蒂米什瓦拉"]),
    "CL": _c("CL", "Chile", "智利", ["56"], ["CLP"], [-4.0],
             (-76.0, -56.0, -66.0, -17.0),
             ["Santiago", "Valparaiso", "Concepcion"],
             ["圣地亚哥", "瓦尔帕莱索", "康塞普西翁"]),
    "CO": _c("CO", "Colombia", "哥伦比亚", ["57"], ["COP"], [-5.0],
             (-79.0, -4.0, -66.0, 13.0),
             ["Bogota", "Medellin", "Cali", "Cartagena"],
             ["波哥大", "麦德林", "卡利", "卡塔赫纳"]),
    "PE": _c("PE", "Peru", "秘鲁", ["51"], ["PEN"], [-5.0],
             (-82.0, -19.0, -68.0, 0.0),
             ["Lima", "Cusco", "Arequipa"],
             ["利马", "库斯科", "阿雷基帕"]),
    "KZ": _c("KZ", "Kazakhstan", "哈萨克斯坦", ["7"], ["KZT"], [5.0, 6.0],
             (46.0, 40.0, 88.0, 56.0),
             ["Almaty", "Astana", "Shymkent"],
             ["阿拉木图", "阿斯塔纳", "奇姆肯特"]),
    "UZ": _c("UZ", "Uzbekistan", "乌兹别克斯坦", ["998"], ["UZS"], [5.0],
             (55.0, 37.0, 74.0, 46.0),
             ["Tashkent", "Samarkand"], ["塔什干", "撒马尔罕"]),
    "LU": _c("LU", "Luxembourg", "卢森堡", ["352"], ["EUR"], [1.0],
             (5.0, 49.0, 7.0, 51.0),
             ["Luxembourg"], ["卢森堡"]),
}
